### ISSUE TITLE
bitstring 4.1.0 with open ended dependency on bitarray >=2.8

### ISSUE THREAD

**Issue by akrherz** [conda-forge/bitstring-feedstock#15]
### Comment:

Greetings.  With `bitarray=3.0` on conda-forge now, the dep solver is wishing to downgrade bitstring to version 4.1.0, which has an [open ended dependency](https://conda-metadata-app.streamlit.app/?q=conda-forge%2Fnoarch%2Fbitstring-4.1.0-pyhd8ed1ab_0.conda) on `bitarray >=2.8.0`

I'll submit a metadata patch for this, but wanted to alert you folks to this.

**Comment by m-rossi** [comment]
@akrherz thanks for the report and patch. Was not aware of such issue until now.
